## Introduction to Tensorflow 2

In [1]:
pip --version

pip 20.2.4 from /Users/Murat/anaconda3/lib/python3.7/site-packages/pip (python 3.7)
Note: you may need to restart the kernel to use updated packages.


In [2]:
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np

In [3]:
print("TF Version:",tf.__version__)

TF Version: 2.3.1


In [4]:
print("eager execution:",tf.executing_eagerly)

eager execution: <function executing_eagerly at 0x7ff0ff523ea0>


In [5]:
print("eager execution:",tf.executing_eagerly())

eager execution: True


In [6]:
print("1+2+3+4 = ",tf.reduce_sum([1,2,3,4]))

1+2+3+4 =  tf.Tensor(10, shape=(), dtype=int32)


### Data Types

In [8]:
tf.int8
tf.int16
tf.int32
tf.int64

tf.uint8
tf.uint16
tf.uint32
tf.uint64

tf.float16
tf.float32
tf.float64

tf.string
tf.bool

tf.bool

### Primitive Types constant and variable

In [11]:
constant_a = tf.constant(3.0,name='a')
constant_a

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

In [12]:
variable_a = tf.Variable(3,name='a')
variable_a

<tf.Variable 'a:0' shape=() dtype=int32, numpy=3>

In [13]:
scalar = tf.constant(10)
vector = tf.constant([1,2,3,4,5])
matrix = tf.constant([[1,2,3],[4,5,6]])
cube = tf.constant([[[1],[2],[3]],[[4],[5],[6]],[[7],[8],[9]]])

print(scalar.get_shape())
print(vector.get_shape())
print(matrix.get_shape())
print(cube.get_shape())

()
(5,)
(2, 3)
(3, 3, 1)


In [14]:
x = tf.Variable(3,name='x')
y = tf.Variable(3,name='y')

#tf.function

def calc_prod(x,y):
    z=2*x+y
    return z

result = calc_prod(x,y)
print('result:',result)

result: tf.Tensor(9, shape=(), dtype=int32)


In [16]:
tf.Variable(tf.random.normal([2,4]))

<tf.Variable 'Variable:0' shape=(2, 4) dtype=float32, numpy=
array([[-0.52843773, -0.69031566, -0.05974954,  0.9682665 ],
       [ 0.28284565, -2.1874433 , -1.7553594 ,  0.1964865 ]],
      dtype=float32)>

In [17]:
v = tf.Variable([[1,2,3],[4,5,6]])
print("v.value:",v.value())
print('')
print('v.numpy:',v.numpy())


v.value: tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)

v.numpy: [[1 2 3]
 [4 5 6]]


In [18]:
v.assign(2*v)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 8, 10, 12]], dtype=int32)>

In [19]:
v[0,1].assign(42)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[ 2, 42,  6],
       [ 8, 10, 12]], dtype=int32)>

In [20]:
v[1].assign([7,8,9])
print("v: ",v)

v:  <tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[ 2, 42,  6],
       [ 7,  8,  9]], dtype=int32)>


In [21]:
try:
    v [1] = [7,8,9]
except TypeError as ex:
    print(ex)

'ResourceVariable' object does not support item assignment


In [23]:
A = tf.constant(3.0)
B = tf.fill([2,3],5.0)
C = tf.constant([3,4])

print(A)
print(B)
print(C)
print("")

tf.Tensor(3.0, shape=(), dtype=float32)
tf.Tensor(
[[5. 5. 5.]
 [5. 5. 5.]], shape=(2, 3), dtype=float32)
tf.Tensor([3 4], shape=(2,), dtype=int32)



In [24]:
def show_rank(x):
    return tf.rank(x)

print('A: ', show_rank(A))
print('B: ', show_rank(B))
print('C: ', show_rank(C))

A:  tf.Tensor(0, shape=(), dtype=int32)
B:  tf.Tensor(2, shape=(), dtype=int32)
C:  tf.Tensor(1, shape=(), dtype=int32)


In [25]:
print('A: ', A.get_shape())
print('B: ', B.get_shape())
print('C: ', C.get_shape())

A:  ()
B:  (2, 3)
C:  (2,)


In [26]:
a = tf.add(4,2)
a

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [27]:
print(a)

tf.Tensor(6, shape=(), dtype=int32)


In [28]:
def compute_values():
    print(a)
    
compute_values()

tf.Tensor(6, shape=(), dtype=int32)


In [29]:
def compute_values():
    a = tf.add(4,2)
    return a

In [30]:
compute_values()

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [31]:
def func():
    a = tf.constant([[10,10],[11.,1.]])
    print(a)
    b = tf.constant([[1.,0.],[0.,1.]])
    print(b)
    c = tf.matmul(a,b)
    print(c)
    return c

In [32]:
func()

tf.Tensor(
[[10. 10.]
 [11.  1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 0.]
 [0. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[10. 10.]
 [11.  1.]], shape=(2, 2), dtype=float32)


<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[10., 10.],
       [11.,  1.]], dtype=float32)>

In [33]:
print(func().numpy)

tf.Tensor(
[[10. 10.]
 [11.  1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 0.]
 [0. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[10. 10.]
 [11.  1.]], shape=(2, 2), dtype=float32)
<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[10., 10.],
       [11.,  1.]], dtype=float32)>>


In [34]:
def add(a):
    return a+a

print('',add(1))
print('',add(2))
print('',add(tf.constant('abc')))

 2
 4
 tf.Tensor(b'abcabc', shape=(), dtype=string)


In [35]:
w = tf.Variable([[2.0]])
print(w)

with tf.GradientTape() as tape:
    loss = w*w*2
    
grad = tape.gradient(loss,w)
# turev = 4 * w
print(grad)

<tf.Variable 'Variable:0' shape=(1, 1) dtype=float32, numpy=array([[2.]], dtype=float32)>
tf.Tensor([[8.]], shape=(1, 1), dtype=float32)


In [44]:
#deneme

w = tf.Variable([[2.0]])
print(w)

with tf.GradientTape() as mm:
    loss = w*w*2
    
grad = mm.gradient(loss,w) # turev = 4 * w
print(grad)

<tf.Variable 'Variable:0' shape=(1, 1) dtype=float32, numpy=array([[2.]], dtype=float32)>
tf.Tensor([[8.]], shape=(1, 1), dtype=float32)


In [37]:
w = tf.Variable([[3.0]])

with tf.GradientTape() as tape:
    loss = w*w*2
    
grad = tape.gradient(loss,w) # turev = 4 * w = 4 * 3 = 12 
print(grad)

tf.Tensor([[12.]], shape=(1, 1), dtype=float32)


In [38]:
w = tf.Variable([[3.0]])

with tf.GradientTape() as tape:
    loss = w*w*w*2
    
grad = tape.gradient(loss,w)  # turev = 6 * w * w = 6*3*3 = 54
print(grad)

tf.Tensor([[54.]], shape=(1, 1), dtype=float32)


In [39]:
x = tf.constant(3.0)

with tf.GradientTape() as q:
    q.watch(x)
    y = 4*x*x
    
dy_dx = q.gradient(y,x) # turev = 8 * x

In [40]:
dy_dx

<tf.Tensor: shape=(), dtype=float32, numpy=24.0>

In [41]:
x = tf.constant(4.0)

with tf.GradientTape() as t1:
    with tf.GradientTape() as t2:
        t1.watch(x)
        t2.watch(x)
        z = x*x*x
    dz_dx = t2.gradient(z,x) # 3*x*x
d2z_dx2 = t1.gradient(dz_dx,x) # 6*x

print("first: ",dz_dx)
print("second: ",d2z_dx2)

first:  tf.Tensor(48.0, shape=(), dtype=float32)
second:  tf.Tensor(24.0, shape=(), dtype=float32)


In [42]:
x = tf.Variable(4.0)

with tf.GradientTape() as t1:
    with tf.GradientTape() as t2:
        t1.watch(x)
        t2.watch(x)
        z = x*x*x
    dz_dx = t2.gradient(z,x) # 3*x*x
d2z_dx2 = t1.gradient(dz_dx,x) # 6*x

print("first: ",dz_dx)
print("second: ",d2z_dx2)

first:  tf.Tensor(48.0, shape=(), dtype=float32)
second:  tf.Tensor(24.0, shape=(), dtype=float32)
